services:
  dspot-test:
    image: omartin9203/dspot-test:latest
    container_name: dspot-test-app
    build:
      context: .
      dockerfile: Dockerfile
      # Only will build development stage from our dockerfile
      target: development
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      POSTGRES_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - mongodb
      - postgres
    command: yarn start:dev
    volumes:
      - ./:/var/www/app

  mongodb:
    image: mongo
    restart: always
    container_name: dspot-test-mongodb
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

  postgres:
    image: postgres
    container_name: dspot-test-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  mongodata: {}
  postgres-db: